In [2]:
import numpy as np

n1=np.array([10,20])
print(n1+10)

[20 30]


In [4]:
n1=np.arange(1,10)
print(n1)

[1 2 3 4 5 6 7 8 9]


import random
n1=np.array((3,4),random.choice(0,1))
n1

In [14]:
import random 
n1=np.random.rand(3, 4)
print(n1)

[[0.83236704 0.11437704 0.43916331 0.38885309]
 [0.40324323 0.98990835 0.74182699 0.56134821]
 [0.27648404 0.81085565 0.75380931 0.71777946]]


In [16]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([5, 6, 7, 8])
print(np.(arr1+arr2))

TypeError: add() takes from 2 to 3 positional arguments but 1 were given

In [17]:
arr = np.array([10, 20, 30, 40, 50])
print(arr+5)

[15 25 35 45 55]


In [19]:
n1=np.concatenate((arr1,arr2))
print(n1)

[1 2 3 4 5 6 7 8]


In [23]:
n1=np.linspace(0,9,10)
print(n1)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [28]:
n2=np.linspace(0,80,7)

In [29]:
n2

array([ 0.        , 13.33333333, 26.66666667, 40.        , 53.33333333,
       66.66666667, 80.        ])

In [31]:
n1=np.full((3,3),3)
n1

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [32]:
n2=np.eye(3)
n2


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr[::-1])

[6 5 4 3 2 1]


In [39]:
arr = np.array([15, 20, 25, 30, 35])
np.mean(arr)

25.0

In [40]:
np.median(arr)

25.0

In [41]:
np.std(arr)

7.0710678118654755

In [42]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.diagonal(arr)

array([1, 5, 9])

In [48]:
n1=np.random.rand(1,101,10)
n1

array([[[0.84347848, 0.48393695, 0.16675771, ..., 0.82788089,
         0.91035396, 0.27842955],
        [0.3014916 , 0.95187922, 0.04952855, ..., 0.7425586 ,
         0.70848653, 0.72807286],
        [0.85132223, 0.06349324, 0.81956651, ..., 0.82189343,
         0.38151689, 0.07983722],
        ...,
        [0.08918312, 0.81461157, 0.90176796, ..., 0.77169691,
         0.23514564, 0.63339596],
        [0.07005173, 0.67599717, 0.79557798, ..., 0.08047556,
         0.81830269, 0.26799654],
        [0.48840089, 0.76111446, 0.14137292, ..., 0.84260394,
         0.14703685, 0.58240897]]])

In [51]:
n2=random.randint(1,51)
n1=np.array((5,5))
n1



array([5, 5])

In [53]:
n1=np.random.randint(1,51,size=(5,5))
n1

array([[39, 41,  1, 25, 41],
       [37, 30, 46, 26, 10],
       [20,  6, 24, 42, 34],
       [ 3, 26, 48, 12, 46],
       [36, 48, 16, 44, 44]])

In [54]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.sum(arr)

45

In [56]:
n1=np.linspace(0,1,100).reshape(10,10)
n1

array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [59]:
arr1 = np.array([1, 2, 3, 4]) 
arr2 = np.array([5, 6, 7, 8])
print(np.intersect1d(arr1,arr2))

[]


In [64]:
n1=np.random.randint(-50,51,10)

n1[n1<0]=0
n1

array([29,  0,  6, 20, 37,  0, 24, 20, 39,  0])

In [71]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
#row=np.sum(arr,axis=1)
#col=np.sum(arr,axis=0)
print(np.sum(col))

45


In [73]:
a=np.array((6,6),diagonal=[1,2,3,4,5,6])
a

TypeError: array() got an unexpected keyword argument 'diagonal'

In [74]:
a=np.diag(np.arange(1,7))
a

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

In [75]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)


[1 2 3 4 5]
[0.   0.25 0.5  0.75 1.  ]


In [87]:
a=np.random.randint(1,101,20)
b=np.max(a)
print(a)
print(b)



[26 38 33 78 26 31 50 31 64 75 13 71 95 21 64 32 18 30 30 49]
95


In [90]:
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
#np.multiply(arr1,arr2)
print(arr1*arr2)

[ 5 12 21 32]


In [95]:


import pandas as pd

s1=pd.series([2, 4, 6, 8, 10])
s2=pd.series([1, 3, 5, 7, 9])
s=s1+s2
print(s)



AttributeError: module 'pandas' has no attribute 'series'

In [100]:

ds1=pd.series([2, 4, 6, 8, 10])
ds2=pd.series([1, 3, 5, 7, 9])
ds=ds1 + ds2
print(ds)

AttributeError: module 'pandas' has no attribute 'series'

In [101]:
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64


In [121]:
data = { 'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 22, 28], 'City': ['New York',
'London', 'Paris', 'Tokyo'] }
pd.DataFrame(data)

Name  Age      City
0    Alice   25  New York
1      Bob   30    London
2  Charlie   22     Paris
3    David   28     Tokyo

In [122]:
df=pd.DataFrame(data)

In [123]:
df.head(2)

Name  Age      City
0  Alice   25  New York
1    Bob   30    London

In [124]:
df['salary']=np.random.randint(50000,80001,len(df))

In [125]:
df

Name  Age      City  salary
0    Alice   25  New York   62117
1      Bob   30    London   78482
2  Charlie   22     Paris   55653
3    David   28     Tokyo   52035

In [136]:
filtered_df=df[df['Age']>25]

In [137]:
filtered_df

Name  Age    City  salary
1    Bob   30  London   78482
3  David   28   Tokyo   52035

In [139]:
new=df.sort_values(by='Age',ascending=True)

In [140]:
new

Name  Age      City  salary
2  Charlie   22     Paris   55653
0    Alice   25  New York   62117
3    David   28     Tokyo   52035
1      Bob   30    London   78482

In [142]:
df=pd.read_csv('nba.csv')

In [143]:
df.shape

(457, 8)

In [144]:
df.head(5)

Name            Team  Number Position  Age  Weight  \
0  Avery Bradley  Boston Celtics       0       PG   25     180   
1    Jae Crowder  Boston Celtics      99       SF   25     235   
2   John Holland  Boston Celtics      30       SG   27     205   
3    R.J. Hunter  Boston Celtics      28       SG   22     185   
4  Jonas Jerebko  Boston Celtics       8       PF   29     231   

             College     Salary  
0              Texas  7730337.0  
1          Marquette  6796117.0  
2  Boston University        NaN  
3      Georgia State  1148640.0  
4                NaN  5000000.0

In [145]:
df.dtypes

Name         object
Team         object
Number        int64
Position     object
Age           int64
Weight        int64
College      object
Salary      float64
dtype: object

In [146]:
df.describe

<bound method NDFrame.describe of               Name            Team  Number Position  Age  Weight  \
0    Avery Bradley  Boston Celtics       0       PG   25     180   
1      Jae Crowder  Boston Celtics      99       SF   25     235   
2     John Holland  Boston Celtics      30       SG   27     205   
3      R.J. Hunter  Boston Celtics      28       SG   22     185   
4    Jonas Jerebko  Boston Celtics       8       PF   29     231   
..             ...             ...     ...      ...  ...     ...   
452     Trey Lyles       Utah Jazz      41       PF   20     234   
453   Shelvin Mack       Utah Jazz       8       PG   26     203   
454      Raul Neto       Utah Jazz      25       PG   24     179   
455   Tibor Pleiss       Utah Jazz      21        C   26     256   
456    Jeff Withey       Utah Jazz      24        C   26     231   

               College     Salary  
0                Texas  7730337.0  
1            Marquette  6796117.0  
2    Boston University        NaN  
3    

In [147]:
df.loc[100:200]

Name                  Team  Number Position  Age  Weight  \
100        Chris Paul  Los Angeles Clippers       3       PG   31     175   
101       Paul Pierce  Los Angeles Clippers      34       SF   38     235   
102    Pablo Prigioni  Los Angeles Clippers       9       PG   39     185   
103         JJ Redick  Los Angeles Clippers       4       SG   31     190   
104     Austin Rivers  Los Angeles Clippers      25       PG   23     200   
..                ...                   ...     ...      ...  ...     ...   
196       Lavoy Allen        Indiana Pacers       5       PF   27     255   
197  Rakeem Christmas        Indiana Pacers      25       PF   24     250   
198       Monta Ellis        Indiana Pacers      11       SG   30     185   
199       Paul George        Indiana Pacers      13       SF   26     220   
200       George Hill        Indiana Pacers       3       PG   30     188   

          College      Salary  
100   Wake Forest  21468695.0  
101        Kansas   3376000.0  
102           NaN    947726.0  
103          Duke   7085000.0  
104          Duke   3110796.0  
..            ...         ...  
196        Temple   4050000.0  
197      Syracuse   1007026.0  
198           NaN  10300000.0  
199  Fresno State  17120106.0  
200         IUPUI   8000000.0  

[101 rows x 8 columns]

In [148]:
df.iloc[100:200]

Name                  Team  Number Position  Age  Weight  \
100        Chris Paul  Los Angeles Clippers       3       PG   31     175   
101       Paul Pierce  Los Angeles Clippers      34       SF   38     235   
102    Pablo Prigioni  Los Angeles Clippers       9       PG   39     185   
103         JJ Redick  Los Angeles Clippers       4       SG   31     190   
104     Austin Rivers  Los Angeles Clippers      25       PG   23     200   
..                ...                   ...     ...      ...  ...     ...   
195  Anthony Tolliver       Detroit Pistons      43       PF   31     240   
196       Lavoy Allen        Indiana Pacers       5       PF   27     255   
197  Rakeem Christmas        Indiana Pacers      25       PF   24     250   
198       Monta Ellis        Indiana Pacers      11       SG   30     185   
199       Paul George        Indiana Pacers      13       SF   26     220   

          College      Salary  
100   Wake Forest  21468695.0  
101        Kansas   3376000.0  
102           NaN    947726.0  
103          Duke   7085000.0  
104          Duke   3110796.0  
..            ...         ...  
195     Creighton   3000000.0  
196        Temple   4050000.0  
197      Syracuse   1007026.0  
198           NaN  10300000.0  
199  Fresno State  17120106.0  

[100 rows x 8 columns]

In [152]:
df.sort_values(by='Number' and 'Salary', ascending=True)

Name                    Team  Number Position  Age  \
32   Thanasis Antetokounmpo         New York Knicks      43       SF   23   
291         Orlando Johnson    New Orleans Pelicans       0       SG   27   
130            Phil Pressey            Phoenix Suns      25       PG   25   
135           Alan Williams            Phoenix Suns      15        C   23   
175            Jordan McRae     Cleveland Cavaliers      12       SG   25   
..                      ...                     ...     ...      ...  ...   
273          Alex Stepheson       Memphis Grizzlies      35       PF   28   
350           Briante Weber              Miami Heat      12       PG   23   
353           Dorell Wright              Miami Heat      11       SF   30   
397            Axel Toupane          Denver Nuggets       6       SG   23   
409              Greg Smith  Minnesota Timberwolves       4       PF   25   

     Weight                College    Salary  
32      205                    NaN   30888.0  
291     220       UC Santa Barbara   55722.0  
130     175               Missouri   55722.0  
135     260       UC Santa Barbara   83397.0  
175     179              Tennessee  111196.0  
..      ...                    ...       ...  
273     270                    USC       NaN  
350     165  Virginia Commonwealth       NaN  
353     205                    NaN       NaN  
397     210                    NaN       NaN  
409     250           Fresno State       NaN  

[457 rows x 8 columns]

In [159]:
df[df['Salary']<100000]

Name                  Team  Number Position  Age  \
32   Thanasis Antetokounmpo       New York Knicks      43       SF   23   
130            Phil Pressey          Phoenix Suns      25       PG   25   
135           Alan Williams          Phoenix Suns      15        C   23   
291         Orlando Johnson  New Orleans Pelicans       0       SG   27   

     Weight           College   Salary  
32      205               NaN  30888.0  
130     175          Missouri  55722.0  
135     260  UC Santa Barbara  83397.0  
291     220  UC Santa Barbara  55722.0

In [162]:
df[df['Name']=='Alan Williams']

Name          Team  Number Position  Age  Weight  \
135  Alan Williams  Phoenix Suns      15        C   23     260   

              College   Salary  
135  UC Santa Barbara  83397.0